#!/usr/bin/env php
<?php

// Connection default parameters
$connectionDefaults = array(
    'scheme'   => 'http',
    'user'     => null,
    'password' => null,
    'host'     => 'localhost',
    'port'     => 5984,
);

$target = parse_url(isset($argv[1]) ? $argv[1] : '/native');
$target += $connectionDefaults;

// Ensure target database is recreated
try {
    request($target, $target['path'], 'DELETE');
} catch ( Exception $e ) {
    // If it did not exis, we do not care
}

// 1) Create database
requestSimple($target, $target['path'], 'PUT');

// 2) Create some data in the database
mt_srand(42);
$users = array();
foreach (array("kore", "hans", "egon") as $user) {
    $users[] = json_decode(request($target, $target['path'] . '/user-' . $user, 'PUT', json_encode(array(
        'type' => 'user',
        'name' => $user,
    ))));
}

$posts = array();
foreach (range(1, 5) as $number) {
    $posts[] = json_decode(request($target, $target['path'] . '/post-hello_world_' . $number, 'PUT', json_encode(array(
        'type'  => 'post',
        'user'  => $users[0]->id,
        'title' => 'Hello world ' . $number,
        'text'  => 'Hello #world! This is blog #post number ' . $number . '.',
        'date'  => date("m d, Y H:i:s", mt_rand(10000000, 20000000)),
    ))));
}

foreach ($posts as $post) {
    for ($i = 0; $i < mt_rand(2, 5); ++$i) {
        $posts[] = json_decode(request($target, $target['path'], 'POST', json_encode(array(
            'type'   => 'post_comment',
            'user'   => $users[array_rand($users)]->id,
            'post'   => $post->id,
            'text'   => 'This is just a random comment',
            'date'   => date("m d, Y H:i:s", mt_rand(10000000, 20000000)),
            'rating' => mt_rand(0, 5),
        ))));
    }
}

// 4) Create a view
request(
    $target,
    $target['path'] . '/_design/blog',
    'PUT',
    json_encode(array(
        '_id'      => '_design/blog',
        'language' => 'javascript',
        'views'    => array(
            // List posts (including comment count)
            'posts' => array(
                'map' => file_get_contents(__DIR__ . '/../views/posts/map.js'),
            ),
            // Per user, show: comments, posts
            'user' => array(
                'map' => file_get_contents(__DIR__ . '/../views/user/map.js'),
            ),
            // Show single post, including comments
            'post' => array(
                'map' => file_get_contents(__DIR__ . '/../views/post/map.js'),
            ),
            // Show average comment count for all posts
            'comments' => array(
                'map' => file_get_contents(__DIR__ . '/../views/comments/map.js'),
                'reduce' => file_get_contents(__DIR__ . '/../views/comments/reduce.js'),
            ),
            // Time range aggregation for comments
            'time_range' => array(
                'map' => file_get_contents(__DIR__ . '/../views/time_range/map.js'),
                'reduce' => file_get_contents(__DIR__ . '/../views/time_range/reduce.js'),
            ),
        )
    ))
);

// 5) Request the view
var_dump(
    json_decode(request(
        $target,
        $target['path'] . '/_design/blog/_view/time_range?group=true&group_level=2'
    ))->rows
);

/***
 * Helper functions
 */

/**
 * Execute a HTTP request
 *
 * Will throw an exception if the server responds with a status >= 400 or on
 * connection failure.
 *
 * Returns the response body on success as a string.
 *
 * @param array $host
 * @param string $path
 * @param string $method
 * @param mixed $data
 * @return string
 */
function request(array $host, $path, $method = 'GET', $data = null)
{
    $httpFilePointer = @fopen(
        $url = $host['scheme'] . '://' . $host['user'] . ':' . $host['password'] . '@' . $host['host']  . ':' . $host['port'] . $path,
        'r',
        false,
        stream_context_create(
            array(
                'http' => array(
                    'method'        => $method,
                    'content'       => $data,
                    'ignore_errors' => true,
                    'header'        => 'Content-type: application/json',
                ),
            )
        )
    );

    // Check if connection has been established successfully
    if ($httpFilePointer === false) {
        throw new Exception("Could not connect to server at $url: " . error_get_last()['message']);
    }

    $body = stream_get_contents($httpFilePointer);

    $metaData   = stream_get_meta_data($httpFilePointer);
    $rawHeaders = isset($metaData['wrapper_data']['headers']) ? $metaData['wrapper_data']['headers'] : $metaData['wrapper_data'];
    $headers    = array();
    foreach ($rawHeaders as $lineContent) {
        // Extract header values
        if (preg_match('(^HTTP/(?P<version>\d+\.\d+)\s+(?P<status>\d+))S', $lineContent, $match)) {
            $headers['version'] = $match['version'];
            $headers['status']  = (int) $match['status'];
        } else {
            list($key, $value) = explode(':', $lineContent, 2);
            $headers[strtolower($key)] = ltrim($value);
        }
    }

    if ($headers['status'] >= 400) {
        throw new Exception("Server returned with error: " . $headers['status'] . " for URL $url\n\n" . $body);
    }

    return $body;
}

function requestSimple(array $host, $path, $method = 'GET', $data = null)
{
    return file_get_contents(
        $host['scheme'] . '://' . $host['user'] . ':' . $host['password'] . '@' . $host['host']  . ':' . $host['port'] . $path,
        false,
        stream_context_create(
            array(
                'http' => array(
                    'method'        => $method,
                    'content'       => $data,
                    'ignore_errors' => true,
                    'header'        => 'Content-type: application/json',
                ),
            )
        )
    );
}

